name: polymer_app
description: Generation and management of polymer application
version: 0.5.0
author: Walletek <hadrien.lejard@gmail.com>
homepage: https://github.com/walletek/polymer_app

executables:
  polymer_app: polymer_app

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  polymer: "^1.0.0-rc.10"
  polymer_app_router: "^0.0.6"
  web_components: "^0.12.0"
  reflectable: "^0.5.1"
  dart_to_js_script_rewriter: "^0.1.0+4"
  args: ^0.13.2
  path: ^1.3.9
  http: ^0.11.3+3
  dart_style: ^0.2.2
  cupid: #^0.9.10
    git: "https://github.com/lejard-h/cupid.git"
    #path: "/Users/lejard_h/github/cupid"

dev_dependencies:
  test: '>=0.12.0'