name: polymer_app
description: Generation and management of polymer application
version: 0.0.7
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/polymer_app

executables:
  polymer_app: polymer_app

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  polymer: "^1.0.0-rc.10"
  args: any
  path: any
  ansicolor: any
  http: any
  dart_style: any
