name: polymer_app
description: Generation and management of polymer application
version: 0.2.0
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/polymer_app

executables:
  polymer_app: polymer_app

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  polymer: "^1.0.0-rc.10"
  polymer_app_router: "^0.0.5"
  args: ^0.13.2
  path: ^1.3.9
  ansicolor: ^0.0.9
  http: ^0.11.3+3
  dart_style: ^0.2.2
